### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by AdamYLiang** [ntomsho/WouldReads#1]
- [x] Have user auth as the second MVP
- [x] Ratings/Reviews should be it's own MVP 
- [x] Read status should be it's own MVP
- [x] Consider making recommendations and search as bonus MVPs 

Let me know if you have any questions or if you want more details!

**Comment by AdamYLiang** [comment]
Nice changes on MVP List. Here are some last changes to make: 
- [x] Add demo user for user auth MVP

Please comment when the above is complete. Keep up the good work!

**Comment by ntomsho** [comment]
Completed

**Comment by AdamYLiang** [comment]
Nice changes, looks good!
